name: Build and upload the master-file LaTeX document
on: 
  push:
    branches: [master]
    paths:
      - 'preamble/**'
      - 'sections/**'
      - 'img/**'  
jobs:
  latex-build:
    name: build main
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: latexmk
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          post_compile: "latexmk -c"
      - name: Upload pdf document
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: releases/main.pdf
